### ISSUE TITLE
Getters are shown as a method instead of property.

### ISSUE THREAD

**Issue by blasten** [PolymerElements/iron-component-page#38] opened 2015-06-24 22:17 UTC
e.g.

```js
    /**
     * Returns the scrollable element.
     *
     * @property scroller
     * @type Object
     */
    get scroller() {
      return null;
    },

```

This is explicitly annotated as a property; however:

![screen shot 2015-06-24 at 3 16 31 pm](https://cloud.githubusercontent.com/assets/1410613/8342828/04775824-1a84-11e5-9807-238efbfa5fbf.png)

**Comment by notwaldorf** [comment] 2016-01-27 22:55
Duplicate of https://github.com/PolymerElements/iron-doc-viewer/issues/46

**Closed by notwaldorf** 2016-01-27 22:55 UTC
Labels: bug
