### ISSUE TITLE
proposal: customElements es6 classes

### ISSUE THREAD

**Issue by gertcuykens** [PolymerElements/iron-component-page#112] opened 2016-09-30 01:35 UTC
iron pages can detect non polymer elements too by introducing a polymer constructor api.

``` js
class HelloWorld extends HTMLElement {                                                                                       
  constructor() {                                                                                                            
    super() 
    // polymer iron page specification                                                                                                               
    let l = document.querySelector('link[rel="import"]')                                                                     
    var t = l.import.querySelector('template')                                                                               
    const instance = t.content.cloneNode(true)                                                                               
    let shadowRoot = this.attachShadow({ mode: 'open' })                                                                     
    shadowRoot.appendChild(instance)                                                                                         
  }                                                                                                                          
}                                                                                                                            
customElements.define('hello-world', HelloWorld)
```

**Comment by arodic** [comment] 2017-07-11 13:54
Also note that iron-component-page currently does not detect Polymer elements defined using new ES6 syntax style. For example :

````javascript
class HelloWorld extends Polymer.Element {}
````

**Comment by justinfagnani** [comment] 2017-07-11 14:42
The Polymer Analyzer already supports non-Polymer elements either by detecting a `customElements.define()` call, or by seeing a `@customElement` JSDoc annotation.

```javascript
class HelloWorld extends Polymer.Element {}
```

should work as long as the class is annotated with `@customElement`, and you'll probably want `@extends Polymer.Element` also.

**Comment by justinfagnani** [comment] 2017-07-11 14:42
Closing this assuming the feature is working as intended. cc @aomarks

**Closed by justinfagnani** 2017-07-11 14:42 UTC
