### ISSUE TITLE
Support aggregated import file of elements

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/iron-component-page#9] opened 2015-05-10 19:52 UTC
We have an import (`google-web-components.html`) with a bunch of other imports in it. The docs do not render those transitive imports. I see `iron-doc-viewer` has `transitive`, but that also will include polymer core lib imports.

![screen shot 2015-05-10 at 12 51 12 pm](https://cloud.githubusercontent.com/assets/238208/7555982/46c6e4b8-f713-11e4-8a8c-51f6480f1b7c.png)

**Comment by mbleigh** [comment] 2015-05-23 07:07
I think this has to be tackled in hydrolysis, though can leave this issue as a marker for making sure it works once hydrolysis supports.

**Comment by atotic** [comment] 2015-05-25 07:24
I am trying to tackle this in hydrolysis-element by making "transitive" take a regex. Hitting code paths less taken....

**Comment by atotic** [comment] 2015-05-26 05:18
I've looked into resolving this by making "transitive" take a regex of files to include transitively, transitive="google*" in your example. It can be done, but I am not sure if it is the right thing to do.

Reassigning to @garlicnation. We can discuss the right way to support this, if at all.

**Comment by garlicnation** [comment] 2015-05-26 18:41
We could support this with a combination of transitive and "filterElements". "filterElements" could be a regex that is used to choose whether or not to display an element.

**Comment by hadfieldn** [comment] 2015-05-28 07:13
First let me just say this component is awesome. Accessing well-formatted documentation for any component like it does is really useful.

I was trying to create a landing page to document a set of components much like I think @ebidel was trying to do, and found that even if I include all the dependent elements by setting `transitive="true"`, the *Demo* link for any of the elements opens to the demo for my own `iron-component-page` rather than the demo associated with the selected element. 

I'm guessing this is by design for aggregations of elements that share a common demo, and perhaps generating documentation for a set of components that have their own demos is beyond the scope of this component. If so, it would be great if there was another component to provide this functionality.

**Comment by atotic** [comment] 2015-05-28 07:22
We are working on supporting multiple demos, there is another bug filed for
it already.

**Comment by hadfieldn** [comment] 2015-05-28 07:25
Dang you guys are fast. Thanks!

**Comment by notwaldorf** [comment] 2016-01-26 23:39
Closing as a duplicate of https://github.com/PolymerElements/iron-doc-viewer/issues/13

**Closed by notwaldorf** 2016-01-26 23:39 UTC
Labels: duplicate, enhancement
