### ISSUE TITLE
Support multiple `demo`'s

### ISSUE THREAD

**Issue by David-Mulder** [PolymerElements/iron-component-page#67] opened 2015-11-14 15:09 UTC
For one the element catalog already supports this, and it kind of sucks that 'we normal people' have to list to an ugly `index.html` instead of a beautiful menu xD

(Looked around and can't find an issue for this, if there is one then I apologize)

**Comment by MeTaNoV** [comment] 2016-02-13 17:45
+1

**Comment by MeTaNoV** [comment] 2016-04-01 08:00
should be related to https://github.com/PolymerElements/iron-component-page/issues/20

**Comment by aomarks** [comment] 2017-06-20 19:17
Duplicate of https://github.com/PolymerElements/iron-component-page/issues/67

**Closed by aomarks** 2017-06-20 19:17 UTC
Labels: p2 - icebox
